apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: a3ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules: 
  - host: joestack.org
    http:
      paths:
      - path: /frontend
        pathType: ImplementationSpecific
        backend:
          service:
            name: client-src
            port:
              number: 5173
      - path: /v1
        pathType: ImplementationSpecific
        backend:
          service:
            name: backend
            port:
              number: 8080
