# Generated by Django 5.0.1 on 2025-04-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_product_alter_order_user"),
        ("users", "0002_remove_user_name_user_username_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="description",
            new_name="billing_address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="shipping_address",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="price",
            new_name="total_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="buyer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Cart", "Cart"),
                    ("Bought", "Bought"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Cart",
                max_length=10,
            ),
        ),
    ]
