# Generated by Django 5.0.1 on 2025-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_rename_description_order_billing_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="date",
            new_name="createDate",
        ),
        migrations.AddField(
            model_name="order",
            name="updateDate",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
