# Generated by Django 5.0.1 on 2025-04-20 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_rename_date_order_createdate_order_updatedate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="buyer_id",
            new_name="user",
        ),
    ]
