# Generated by Django 5.0.1 on 2025-04-20 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_rename_buyer_id_order_user"),
        ("users", "0002_remove_user_name_user_username_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_amount",
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
            ),
        ),
    ]
