# Generated by Django 5.0.1 on 2025-04-21 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cart_billing_address_cart_shipping_address_and_more"),
        ("orders", "0009_remove_order_createdate_remove_order_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="billing_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.AddField(
            model_name="order",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="cart.cart",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Recieved", "Recieved"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Recieved",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
