# Generated by Django 5.0.1 on 2025-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_remove_order_billing_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Received", "Received"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                ],
                default="Received",
                max_length=10,
            ),
        ),
    ]
