# Generated by Django 5.0.1 on 2025-04-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_createdate_cart_created_at_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="billing_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="cart",
            name="shipping_address",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("Cart", "Cart"), ("Paid", "Paid")],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
