# Generated by Django 5.0.1 on 2025-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_brand_product_image_product_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="id",
            new_name="productID",
        ),
    ]
