# Generated by Django 5.0.1 on 2025-04-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_rename_id_product_productid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="productID",
            new_name="id",
        ),
    ]
