# Generated by Django 5.0.1 on 2025-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_productid_product_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archive", "Archive")],
                default="active",
                max_length=10,
            ),
        ),
    ]
